### ISSUE TITLE
Fix code scanning alert

### ISSUE THREAD

**Issue by kortemik** [teragrep/cfe_16#26]
Tracking issue for:
- [ ] https://github.com/teragrep/cfe_16/security/code-scanning/1

**Comment by StrongestNumber9** [comment]
Added a WIP PR for it but why is this implemented by string replacing channel and extras? Is the input format defined by external application because that looks fairly weird.

**Comment by StrongestNumber9** [comment]
Looked into it and it seems like input is arbitrary format json-like strings that are string manipulated later on. This is very fragile approach and I think the input should also be either valid json or as different fields so we can leverage existing tools and methods to do the hard work for us. Currently required param is optional but anything except exact match will cause request body cleaner to return invalid json.
